# Generated by Django 4.2 on 2023-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBuy', '0012_alter_seller_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='picture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
