# Generated by Django 4.2 on 2023-05-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBuy', '0010_seller_cutomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomer',
            new_name='Customer',
        ),
    ]
